// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.30.0--dev
// source: proto/registrar.proto

package petpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_Cat Kind = 0
	Kind_Dog Kind = 1
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "Cat",
		1: "Dog",
	}
	Kind_value = map[string]int32{
		"Cat": 0,
		"Dog": 1,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_registrar_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_proto_registrar_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Fur_Kind int32

const (
	Fur_Short Fur_Kind = 0
	Fur_Long  Fur_Kind = 1
)

// Enum value maps for Fur_Kind.
var (
	Fur_Kind_name = map[int32]string{
		0: "Short",
		1: "Long",
	}
	Fur_Kind_value = map[string]int32{
		"Short": 0,
		"Long":  1,
	}
)

func (x Fur_Kind) Enum() *Fur_Kind {
	p := new(Fur_Kind)
	*p = x
	return p
}

func (x Fur_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Fur_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_registrar_proto_enumTypes[1].Descriptor()
}

func (Fur_Kind) Type() protoreflect.EnumType {
	return &file_proto_registrar_proto_enumTypes[1]
}

func (x Fur_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Fur struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kind        Fur_Kind               `protobuf:"varint,1,opt,name=kind,enum=humus.example.pet.Fur_Kind"`
	xxx_hidden_Color       *string                `protobuf:"bytes,2,opt,name=color"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Fur) Reset() {
	*x = Fur{}
	mi := &file_proto_registrar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fur) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fur) ProtoMessage() {}

func (x *Fur) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registrar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Fur) GetKind() Fur_Kind {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Kind
		}
	}
	return Fur_Short
}

func (x *Fur) GetColor() string {
	if x != nil {
		if x.xxx_hidden_Color != nil {
			return *x.xxx_hidden_Color
		}
		return ""
	}
	return ""
}

func (x *Fur) SetKind(v Fur_Kind) {
	x.xxx_hidden_Kind = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Fur) SetColor(v string) {
	x.xxx_hidden_Color = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Fur) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Fur) HasColor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Fur) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Kind = Fur_Short
}

func (x *Fur) ClearColor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Color = nil
}

type Fur_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Kind  *Fur_Kind
	Color *string
}

func (b0 Fur_builder) Build() *Fur {
	m0 := &Fur{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Kind = *b.Kind
	}
	if b.Color != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Color = b.Color
	}
	return m0
}

type RegisterPetRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Age         uint64                 `protobuf:"varint,1,opt,name=age"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Kind        Kind                   `protobuf:"varint,3,opt,name=kind,enum=humus.example.pet.Kind"`
	xxx_hidden_Breed       *string                `protobuf:"bytes,4,opt,name=breed"`
	xxx_hidden_Fur         *Fur                   `protobuf:"bytes,5,opt,name=fur"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterPetRequest) Reset() {
	*x = RegisterPetRequest{}
	mi := &file_proto_registrar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPetRequest) ProtoMessage() {}

func (x *RegisterPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registrar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterPetRequest) GetAge() uint64 {
	if x != nil {
		return x.xxx_hidden_Age
	}
	return 0
}

func (x *RegisterPetRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *RegisterPetRequest) GetKind() Kind {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Kind
		}
	}
	return Kind_Cat
}

func (x *RegisterPetRequest) GetBreed() string {
	if x != nil {
		if x.xxx_hidden_Breed != nil {
			return *x.xxx_hidden_Breed
		}
		return ""
	}
	return ""
}

func (x *RegisterPetRequest) GetFur() *Fur {
	if x != nil {
		return x.xxx_hidden_Fur
	}
	return nil
}

func (x *RegisterPetRequest) SetAge(v uint64) {
	x.xxx_hidden_Age = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *RegisterPetRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *RegisterPetRequest) SetKind(v Kind) {
	x.xxx_hidden_Kind = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *RegisterPetRequest) SetBreed(v string) {
	x.xxx_hidden_Breed = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *RegisterPetRequest) SetFur(v *Fur) {
	x.xxx_hidden_Fur = v
}

func (x *RegisterPetRequest) HasAge() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterPetRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterPetRequest) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RegisterPetRequest) HasBreed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *RegisterPetRequest) HasFur() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Fur != nil
}

func (x *RegisterPetRequest) ClearAge() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Age = 0
}

func (x *RegisterPetRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *RegisterPetRequest) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Kind = Kind_Cat
}

func (x *RegisterPetRequest) ClearBreed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Breed = nil
}

func (x *RegisterPetRequest) ClearFur() {
	x.xxx_hidden_Fur = nil
}

type RegisterPetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Age   *uint64
	Name  *string
	Kind  *Kind
	Breed *string
	Fur   *Fur
}

func (b0 RegisterPetRequest_builder) Build() *RegisterPetRequest {
	m0 := &RegisterPetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Age != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Age = *b.Age
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Name = b.Name
	}
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Kind = *b.Kind
	}
	if b.Breed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Breed = b.Breed
	}
	x.xxx_hidden_Fur = b.Fur
	return m0
}

type RegisterPetResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_TempName    *string                `protobuf:"bytes,2,opt,name=temp_name,json=tempName"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterPetResponse) Reset() {
	*x = RegisterPetResponse{}
	mi := &file_proto_registrar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPetResponse) ProtoMessage() {}

func (x *RegisterPetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registrar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterPetResponse) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *RegisterPetResponse) GetTempName() string {
	if x != nil {
		if x.xxx_hidden_TempName != nil {
			return *x.xxx_hidden_TempName
		}
		return ""
	}
	return ""
}

func (x *RegisterPetResponse) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *RegisterPetResponse) SetTempName(v string) {
	x.xxx_hidden_TempName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RegisterPetResponse) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterPetResponse) HasTempName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterPetResponse) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *RegisterPetResponse) ClearTempName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TempName = nil
}

type RegisterPetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id       *string
	TempName *string
}

func (b0 RegisterPetResponse_builder) Build() *RegisterPetResponse {
	m0 := &RegisterPetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	if b.TempName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_TempName = b.TempName
	}
	return m0
}

var File_proto_registrar_proto protoreflect.FileDescriptor

var file_proto_registrar_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x68, 0x75, 0x6d, 0x75, 0x73, 0x2e, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x65, 0x74, 0x22, 0x69, 0x0a, 0x03, 0x46, 0x75,
	0x72, 0x12, 0x2f, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1b, 0x2e, 0x68, 0x75, 0x6d, 0x75, 0x73, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x70, 0x65, 0x74, 0x2e, 0x46, 0x75, 0x72, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x1b, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64,
	0x12, 0x09, 0x0a, 0x05, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4c,
	0x6f, 0x6e, 0x67, 0x10, 0x01, 0x22, 0xa7, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x50, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x17, 0x2e, 0x68, 0x75, 0x6d, 0x75, 0x73, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x70, 0x65, 0x74, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x62, 0x72, 0x65, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x62, 0x72, 0x65, 0x65, 0x64, 0x12, 0x28, 0x0a, 0x03, 0x66, 0x75, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x68, 0x75, 0x6d, 0x75, 0x73, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2e, 0x70, 0x65, 0x74, 0x2e, 0x46, 0x75, 0x72, 0x52, 0x03, 0x66, 0x75, 0x72, 0x22,
	0x42, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6d, 0x70, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x2a, 0x18, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x07, 0x0a, 0x03, 0x43,
	0x61, 0x74, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x6f, 0x67, 0x10, 0x01, 0x32, 0x69, 0x0a,
	0x09, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x12, 0x5c, 0x0a, 0x0b, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x65, 0x74, 0x12, 0x25, 0x2e, 0x68, 0x75, 0x6d, 0x75,
	0x73, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x65, 0x74, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x26, 0x2e, 0x68, 0x75, 0x6d, 0x75, 0x73, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x70, 0x65, 0x74, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x35, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x68, 0x75,
	0x6d, 0x75, 0x73, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x65, 0x74, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x65, 0x74, 0x70, 0x62, 0x62,
	0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70, 0xe8, 0x07,
})

var file_proto_registrar_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_registrar_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_registrar_proto_goTypes = []any{
	(Kind)(0),                   // 0: humus.example.pet.Kind
	(Fur_Kind)(0),               // 1: humus.example.pet.Fur.Kind
	(*Fur)(nil),                 // 2: humus.example.pet.Fur
	(*RegisterPetRequest)(nil),  // 3: humus.example.pet.RegisterPetRequest
	(*RegisterPetResponse)(nil), // 4: humus.example.pet.RegisterPetResponse
}
var file_proto_registrar_proto_depIdxs = []int32{
	1, // 0: humus.example.pet.Fur.kind:type_name -> humus.example.pet.Fur.Kind
	0, // 1: humus.example.pet.RegisterPetRequest.kind:type_name -> humus.example.pet.Kind
	2, // 2: humus.example.pet.RegisterPetRequest.fur:type_name -> humus.example.pet.Fur
	3, // 3: humus.example.pet.Registrar.RegisterPet:input_type -> humus.example.pet.RegisterPetRequest
	4, // 4: humus.example.pet.Registrar.RegisterPet:output_type -> humus.example.pet.RegisterPetResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_registrar_proto_init() }
func file_proto_registrar_proto_init() {
	if File_proto_registrar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_registrar_proto_rawDesc), len(file_proto_registrar_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_registrar_proto_goTypes,
		DependencyIndexes: file_proto_registrar_proto_depIdxs,
		EnumInfos:         file_proto_registrar_proto_enumTypes,
		MessageInfos:      file_proto_registrar_proto_msgTypes,
	}.Build()
	File_proto_registrar_proto = out.File
	file_proto_registrar_proto_goTypes = nil
	file_proto_registrar_proto_depIdxs = nil
}
