# Copyright (c) 2024 Z5Labs and Contributors
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

otel:
  resource:
    service_name: {{env "OTEL_SERVICE_NAME" | default ""}}
    service_version: {{env "OTEL_SERVICE_VERSION" | default ""}}

  trace:
    processor:
      type: {{env "OTEL_TRACE_PROCESSOR" | default "batch"}}
      batch:
        export_interval: {{env "OTEL_TRACE_EXPORT_BATCH_INTERVAL" | default "10s"}}
        max_size: {{env "OTEL_TRACE_MAX_BATCH_SIZE" | default 25}}

    sampling:
      ratio: {{env "OTEL_SAMPLING" | default 0.1}}

    exporter:
      type: {{env "OTEL_TRACE_EXPORTER"}}
      otlp:
        type: {{env "OTEL_OTLP_CONN_TYPE" | default "grpc"}}
        target: {{env "OTEL_OTLP_TARGET"}}

  metric:
    reader:
      type: {{env "OTEL_METRIC_READER" | default "periodic"}}
      periodic:
        export_interval: {{env "OTEL_METRIC_EXPORT_INTERVAL" | default "30s"}}

    exporter:
      type: {{env "OTEL_METRIC_EXPORTER"}}
      otlp:
        type: {{env "OTEL_OTLP_CONN_TYPE" | default "grpc"}}
        target: {{env "OTEL_OTLP_TARGET"}}

  log:
    processor:
      type: {{env "OTEL_LOG_PROCESSOR" | default "batch"}}
      batch:
        export_interval: {{env "OTEL_LOG_EXPORT_BATCH_INTERVAL" | default "1s"}}
        max_size: {{env "OTEL_LOG_MAX_BATCH_SIZE" | default 25}}

    exporter:
      type: {{env "OTEL_LOG_EXPORTER"}}
      otlp:
        type: {{env "OTEL_OTLP_CONN_TYPE" | default "grpc"}}
        target: {{env "OTEL_OTLP_TARGET"}}