// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0--dev
// source: example/petstore/petstore.proto

package petstorepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Pet) Reset() {
	*x = Pet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_petstore_petstore_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pet) ProtoMessage() {}

func (x *Pet) ProtoReflect() protoreflect.Message {
	mi := &file_example_petstore_petstore_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pet.ProtoReflect.Descriptor instead.
func (*Pet) Descriptor() ([]byte, []int) {
	return file_example_petstore_petstore_proto_rawDescGZIP(), []int{0}
}

func (x *Pet) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AddPetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pet *Pet `protobuf:"bytes,1,opt,name=pet,proto3" json:"pet,omitempty"`
}

func (x *AddPetRequest) Reset() {
	*x = AddPetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_petstore_petstore_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPetRequest) ProtoMessage() {}

func (x *AddPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_petstore_petstore_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPetRequest.ProtoReflect.Descriptor instead.
func (*AddPetRequest) Descriptor() ([]byte, []int) {
	return file_example_petstore_petstore_proto_rawDescGZIP(), []int{1}
}

func (x *AddPetRequest) GetPet() *Pet {
	if x != nil {
		return x.Pet
	}
	return nil
}

type AddPetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pet *Pet `protobuf:"bytes,1,opt,name=pet,proto3" json:"pet,omitempty"`
}

func (x *AddPetResponse) Reset() {
	*x = AddPetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_petstore_petstore_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPetResponse) ProtoMessage() {}

func (x *AddPetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_petstore_petstore_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPetResponse.ProtoReflect.Descriptor instead.
func (*AddPetResponse) Descriptor() ([]byte, []int) {
	return file_example_petstore_petstore_proto_rawDescGZIP(), []int{2}
}

func (x *AddPetResponse) GetPet() *Pet {
	if x != nil {
		return x.Pet
	}
	return nil
}

type FindPetByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pet *Pet `protobuf:"bytes,1,opt,name=pet,proto3" json:"pet,omitempty"`
}

func (x *FindPetByIdResponse) Reset() {
	*x = FindPetByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_petstore_petstore_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindPetByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPetByIdResponse) ProtoMessage() {}

func (x *FindPetByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_petstore_petstore_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPetByIdResponse.ProtoReflect.Descriptor instead.
func (*FindPetByIdResponse) Descriptor() ([]byte, []int) {
	return file_example_petstore_petstore_proto_rawDescGZIP(), []int{3}
}

func (x *FindPetByIdResponse) GetPet() *Pet {
	if x != nil {
		return x.Pet
	}
	return nil
}

type ListPetsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pet []*Pet `protobuf:"bytes,1,rep,name=pet,proto3" json:"pet,omitempty"`
}

func (x *ListPetsResponse) Reset() {
	*x = ListPetsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_petstore_petstore_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetsResponse) ProtoMessage() {}

func (x *ListPetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_petstore_petstore_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetsResponse.ProtoReflect.Descriptor instead.
func (*ListPetsResponse) Descriptor() ([]byte, []int) {
	return file_example_petstore_petstore_proto_rawDescGZIP(), []int{4}
}

func (x *ListPetsResponse) GetPet() []*Pet {
	if x != nil {
		return x.Pet
	}
	return nil
}

var File_example_petstore_petstore_proto protoreflect.FileDescriptor

var file_example_petstore_petstore_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x65, 0x74, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2f, 0x70, 0x65, 0x74, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x70, 0x65, 0x74, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x22, 0x29, 0x0a, 0x03, 0x50,
	0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x30, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x50, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x03, 0x70, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x65, 0x74, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e,
	0x50, 0x65, 0x74, 0x52, 0x03, 0x70, 0x65, 0x74, 0x22, 0x31, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x50,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x03, 0x70, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x65, 0x74, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2e, 0x50, 0x65, 0x74, 0x52, 0x03, 0x70, 0x65, 0x74, 0x22, 0x36, 0x0a, 0x13, 0x46,
	0x69, 0x6e, 0x64, 0x50, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1f, 0x0a, 0x03, 0x70, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x70, 0x65, 0x74, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x50, 0x65, 0x74, 0x52, 0x03,
	0x70, 0x65, 0x74, 0x22, 0x33, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x03, 0x70, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x65, 0x74, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e,
	0x50, 0x65, 0x74, 0x52, 0x03, 0x70, 0x65, 0x74, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x35, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x65, 0x74, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70,
	0x65, 0x74, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_example_petstore_petstore_proto_rawDescOnce sync.Once
	file_example_petstore_petstore_proto_rawDescData = file_example_petstore_petstore_proto_rawDesc
)

func file_example_petstore_petstore_proto_rawDescGZIP() []byte {
	file_example_petstore_petstore_proto_rawDescOnce.Do(func() {
		file_example_petstore_petstore_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_petstore_petstore_proto_rawDescData)
	})
	return file_example_petstore_petstore_proto_rawDescData
}

var file_example_petstore_petstore_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_example_petstore_petstore_proto_goTypes = []interface{}{
	(*Pet)(nil),                 // 0: petstore.Pet
	(*AddPetRequest)(nil),       // 1: petstore.AddPetRequest
	(*AddPetResponse)(nil),      // 2: petstore.AddPetResponse
	(*FindPetByIdResponse)(nil), // 3: petstore.FindPetByIdResponse
	(*ListPetsResponse)(nil),    // 4: petstore.ListPetsResponse
}
var file_example_petstore_petstore_proto_depIdxs = []int32{
	0, // 0: petstore.AddPetRequest.pet:type_name -> petstore.Pet
	0, // 1: petstore.AddPetResponse.pet:type_name -> petstore.Pet
	0, // 2: petstore.FindPetByIdResponse.pet:type_name -> petstore.Pet
	0, // 3: petstore.ListPetsResponse.pet:type_name -> petstore.Pet
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_example_petstore_petstore_proto_init() }
func file_example_petstore_petstore_proto_init() {
	if File_example_petstore_petstore_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_example_petstore_petstore_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_petstore_petstore_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_petstore_petstore_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_petstore_petstore_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindPetByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_petstore_petstore_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPetsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_petstore_petstore_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_petstore_petstore_proto_goTypes,
		DependencyIndexes: file_example_petstore_petstore_proto_depIdxs,
		MessageInfos:      file_example_petstore_petstore_proto_msgTypes,
	}.Build()
	File_example_petstore_petstore_proto = out.File
	file_example_petstore_petstore_proto_rawDesc = nil
	file_example_petstore_petstore_proto_goTypes = nil
	file_example_petstore_petstore_proto_depIdxs = nil
}
