# Copyright (c) 2024 Z5Labs and Contributors
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

openapi:
  title: {{env "OPENAPI_TITLE"}}
  version: {{env "OPENAPI_VERSION"}}

http:
  port: {{env "HTTP_PORT" | default 8080}}