# Copyright (c) 2024 Z5Labs and Contributors
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

http:
  port: {{env "HTTP_PORT" | default 8080}}

openapi:
  title: {{env "OTEL_SERVICE_NAME" | default ""}}
  version: {{env "OTEL_SERVICE_VERSION" | default ""}}